TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID_HERE"

MQTT_BROKER = "broker.hivemq.com"
MQTT_PORT = 1883
MQTT_TOPIC = "coldchain/shipment"

TEMP_MIN = 2.0
TEMP_MAX = 8.0
HUMIDITY_MIN = 30.0
HUMIDITY_MAX = 70.0

SHIPMENT_ID = "SHIPMENT_1234"
DRIVER_NAME = "Rajesh Kumar"
VEHICLE_NUMBER = "TN-01-AB-1234"

DATA_FILE = "data/sample_data.csv"
MODEL_PATH = "ml/model/lstm_model.keras"
REPORT_OUTPUT = "reports/"
LOOKAHEAD_MINUTES = 15
ANOMALY_THRESHOLD = 0.85
